=== jme-admin-ch/jme-message-type-registry/schema/CommandDescriptor.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Command Descriptor",
  "description": "JSON schema for command descriptors",
  "$ref": "#/definitions/CommandDescriptor",
  "definitions": {
    "CommandDescriptor": {
      "type": "object",
      "properties": {
        "commandName": {
          "type": "string",
          "minLength": 10
        },
        "definingSystem": {
          "type": "string",
          "minLength": 2
        },
        "description": {
          "type": "string"
        },
        "documentationUrl": {
          "$ref": "common.schema.json#/definitions/url"
        },
        "scope": {
          "type": "string",
          "enum": [
            "public",
            "internal"
          ]
        },
        "topic": {
          "type": "string"
        },
        "compatibilityMode": {
          "$ref": "common.schema.json#/definitions/compatibilityMode"
        },
        "versions": {
          "$ref": "common.schema.json#/definitions/Versions"
        }
      },
      "required": [
        "commandName",
        "description",
        "scope"
      ],
      "additionalProperties": false
    }
  }
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/command/jmecreatedeclarationv2command/JmeCreateDeclarationV2Command.json
{
  "commandName": "JmeCreateDeclarationV2Command",
  "definingSystem": "JME",
  "description": "Initiate the creation of a customs declaration.",
  "documentationUrl": "https://confluence.bit.admin.ch/display/JEAP/JmeCreateDeclarationCommand",
  "topic": "jme-messaging-create-declaration-v2",
  "scope": "public",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeCreateDeclarationV2Command_v1.0.0.avdl",
      "compatibilityMode": "BACKWARD"
    },
    {
      "version": "1.1.0",
      "valueSchema": "JmeCreateDeclarationV2Command_v1.1.0.avdl",
      "compatibilityMode": "FULL"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/command/jmecancelracecommand/JmeCancelRaceCommand.json
{
  "commandName": "JmeCancelRaceCommand",
  "description": "Race committee decided to cancel an ongoing race",
  "definingSystem": "JME",
  "topic": "jme-race-cancelrace",
  "scope": "internal",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeCancelRaceCommand_v1.0.0.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/command/jmecreatedeclarationcommand/JmeCreateDeclarationCommand.json
{
  "commandName": "JmeCreateDeclarationCommand",
  "definingSystem": "JME",
  "description": "Initiate the creation of a customs declaration.",
  "documentationUrl": "https://confluence.bit.admin.ch/display/JEAP/JmeCreateDeclarationCommand",
  "topic": "jme-messaging-create-declaration",
  "scope": "public",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeCreateDeclarationCommand_v1.0.0.avdl"
    },
    {
      "version": "1.1.0",
      "valueSchema": "JmeCreateDeclarationCommand_v1.1.0.avdl",
      "compatibilityMode": "BACKWARD"
    },
    {
      "version": "2.0.0",
      "valueSchema": "JmeCreateDeclarationCommand_v2.0.0.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/command/jmecreatetransitdocumentcommand/JmeCreateTransitDocumentCommand.json
{
  "commandName": "JmeCreateTransitDocumentCommand",
  "definingSystem": "JME",
  "description": "Initiate the creation of a transit document (OpenSearch example service).",
  "topic": "jme-create-transit-document",
  "scope": "internal",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeCreateTransitDocumentCommand_v1.0.0.avdl",
      "compatibilityMode": "FULL"
    }
  ]
}
