=== jme-admin-ch/jme-message-type-registry/schema/EventDescriptor.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Event Descriptor",
  "description": "JSON schema for event descriptors",
  "$ref": "#/definitions/EventDescriptor",
  "definitions": {
    "EventDescriptor": {
      "type": "object",
      "properties": {
        "eventName": {
          "type": "string",
          "minLength": 10
        },
        "definingSystem": {
          "type": "string",
          "minLength": 2
        },
        "publishingSystem": {
          "type": "string",
          "minLength": 2,
          "$comment": "deprecated - use definingSystem"
        },
        "description": {
          "type": "string"
        },
        "documentationUrl": {
          "$ref": "common.schema.json#/definitions/url"
        },
        "scope": {
          "type": "string",
          "enum": [
            "public",
            "internal"
          ]
        },
        "topic": {
          "type": "string"
        },
        "compatibilityMode": {
          "$ref": "common.schema.json#/definitions/compatibilityMode"
        },
        "versions": {
          "$ref": "common.schema.json#/definitions/Versions"
        }
      },
      "required": [
        "eventName",
        "description",
        "scope"
      ],
      "anyOf": [
        {
          "required": [
            "publishingSystem"
          ]
        },
        {
          "required": [
            "definingSystem"
          ]
        }
      ],
      "additionalProperties": false
    }
  }
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmeracecarpostchecksplannedevent/JmeRaceCarPostChecksPlannedEvent.json
{
  "eventName": "JmeRaceCarPostChecksPlannedEvent",
  "description": "At least one post-check was planned for a race car",
  "publishingSystem": "JME",
  "scope": "internal",
  "topic": "jme-race-carpostchecks-planned",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeRaceCarPostChecksPlannedEvent_v1.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmeracecarpostcheckscompletedevent/JmeRaceCarPostChecksCompletedEvent.json
{
  "eventName": "JmeRaceCarPostChecksCompletedEvent",
  "description": "Post race checks on selected cars were completed.",
  "publishingSystem": "JME",
  "scope": "internal",
  "topic": "jme-race-carpostchecks-completed",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeRaceCarPostChecksCompletedEvent_v1.0.0.avdl"
    },
    {
      "version": "1.0.1",
      "valueSchema": "JmeRaceCarPostChecksCompletedEvent_v1.0.1.avdl"
    },
    {
      "version": "1.0.2",
      "valueSchema": "JmeRaceCarPostChecksCompletedEvent_v1.0.2.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmeracecarmaintenancerequiredevent/JmeRaceCarMaintenanceRequiredEvent.json
{
  "eventName": "JmeRaceCarMaintenanceRequiredEvent",
  "description": "Racecar needs a maintenance stop",
  "publishingSystem": "JME",
  "topic": "jme-race-maintenance-required",
  "scope": "internal",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeRaceCarMaintenanceRequiredEvent_v1.avdl"
    },
    {
      "version": "2.0.0",
      "valueSchema": "JmeRaceCarMaintenanceRequiredEvent_v2.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmeracemobilecheckpointplannedevent/JmeRaceMobileCheckpointPlannedEvent.json
{
  "eventName": "JmeRaceMobileCheckpointPlannedEvent",
  "description": "At least one mobile control point was planned for a race",
  "publishingSystem": "JME",
  "scope": "internal",
  "topic": "jme-race-mobilecheckpoint-planned",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeRaceMobileCheckpointPlannedEvent_v1.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmediagramversioncreatedevent/JmeDiagramVersionCreatedEvent.json
{
  "eventName": "JmeDiagramVersionCreatedEvent",
  "publishingSystem": "JME",
  "description": "Notification that a new diagram version has been created.",
  "documentationUrl": "https://confluence.bit.admin.ch/display/JEAP/TODO",
  "topic": "jme-process-archive-diagramversioncreated",
  "scope": "internal",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeDiagramVersionCreatedEvent_v1.0.0.avdl",
      "compatibilityMode": "FORWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmeorderpreparedevent/JmeOrderPreparedEvent.json
{
  "eventName": "JmeOrderPreparedEvent",
  "description": "Order prepared (sequential inbox example)",
  "publishingSystem": "JME",
  "topic": "jme-order-prepared",
  "scope": "public",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeOrderPreparedEvent_v1.avdl"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmedeclarationcreatedevent/JmeDeclarationCreatedEvent.json
{
  "eventName": "JmeDeclarationCreatedEvent",
  "publishingSystem": "JME",
  "description": "Customs declaration created event",
  "documentationUrl": "https://confluence.bit.admin.ch/display/JEAP/JmeDeclarationCreatedEvent",
  "topic": "jme-messaging-declaration-created",
  "scope": "internal",
  "versions": [
    {
      "version": "1.1.0",
      "valueSchema": "JmeDeclarationCreatedEvent_v1.avdl",
      "keySchema": "JmeDeclarationCreatedEvent_key_v1.avdl"
    },
    {
      "version": "1.2.0",
      "valueSchema": "JmeDeclarationCreatedEvent_v2.avdl",
      "keySchema": "JmeDeclarationCreatedEvent_key_v2.avdl"
    },
    {
      "version": "1.3.0",
      "valueSchema": "JmeDeclarationCreatedEvent_v3.avdl",
      "keySchema": "ch.admin.bit.jme.declaration.BeanReferenceMessageKey.avdl"
    },
    {
      "version": "1.4.0",
      "valueSchema": "JmeDeclarationCreatedEvent_v4.avdl",
      "keySchema": "ch.admin.bit.jme.declaration.BeanReferenceMessageKey.avdl"
    },
    {
      "version": "1.4.1",
      "valueSchema": "JmeDeclarationCreatedEvent_v1.4.1.avdl",
      "keySchema": "ch.admin.bit.jme.declaration.BeanReferenceMessageKey.avdl",
      "compatibilityMode": "FORWARD"
    },
    {
      "version": "1.5.0",
      "valueSchema": "JmeDeclarationCreatedEvent_v5.avdl",
      "keySchema": "ch.admin.bit.jme.declaration.BeanReferenceMessageKey.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmeracedestinationreachedevent/JmeRaceDestinationReachedEvent.json
{
  "eventName": "JmeRaceDestinationReachedEvent",
  "description": "Racer reached destination",
  "publishingSystem": "JME",
  "topic": "jme-race-destination-reached",
  "scope": "internal",
  "versions": [
    {
      "version": "1.1.0",
      "valueSchema": "JmeRaceDestinationReachedEvent_v1.avdl"
    },
    {
      "version": "2.0.0",
      "valueSchema": "JmeRaceDestinationReachedEvent_v2.avdl"
    },
    {
      "version": "2.0.1",
      "valueSchema": "JmeRaceDestinationReachedEvent_v2.avdl",
      "compatibilityMode": "NONE"
    },
    {
      "version": "3.0.0",
      "valueSchema": "JmeRaceDestinationReachedEvent_v3.avdl",
      "compatibilityMode": "BACKWARD"
    },
    {
      "version": "4.0.0",
      "valueSchema": "JmeRaceDestinationReachedEvent_v4.avdl",
      "compatibilityMode": "FULL"
    }
  ]
}
