=== jme-admin-ch/jme-message-type-registry/schema/EventDescriptor.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Event Descriptor",
  "description": "JSON schema for event descriptors",
  "$ref": "#/definitions/EventDescriptor",
  "definitions": {
    "EventDescriptor": {
      "type": "object",
      "properties": {
        "eventName": {
          "type": "string",
          "minLength": 10
        },
        "definingSystem": {
          "type": "string",
          "minLength": 2
        },
        "publishingSystem": {
          "type": "string",
          "minLength": 2,
          "$comment": "deprecated - use definingSystem"
        },
        "description": {
          "type": "string"
        },
        "documentationUrl": {
          "$ref": "common.schema.json#/definitions/url"
        },
        "scope": {
          "type": "string",
          "enum": [
            "public",
            "internal"
          ]
        },
        "topic": {
          "type": "string"
        },
        "compatibilityMode": {
          "$ref": "common.schema.json#/definitions/compatibilityMode"
        },
        "versions": {
          "$ref": "common.schema.json#/definitions/Versions"
        }
      },
      "required": [
        "eventName",
        "description",
        "scope"
      ],
      "anyOf": [
        {
          "required": [
            "publishingSystem"
          ]
        },
        {
          "required": [
            "definingSystem"
          ]
        }
      ],
      "additionalProperties": false
    }
  }
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmedocumentreviewedevent/JmeDocumentReviewedEvent.json
{
  "eventName": "JmeDocumentReviewedEvent",
  "publishingSystem": "JME",
  "description": "Notification that a document has been reviewed",
  "documentationUrl": "https://confluence.bit.admin.ch/display/JEAP/TODO",
  "topic": "jme-document-reviewed",
  "scope": "internal",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeDocumentReviewedEvent_v1.0.0.avdl",
      "compatibilityMode": "FORWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmetestcreatedevent/JmeTestCreatedEvent.json
{
  "eventName": "JmeTestCreatedEvent",
  "description": "Test event to be deleted",
  "publishingSystem": "JME",
  "topic": "jme-test-created",
  "scope": "public",
  "versions": [
    {
      "version": "0.0.1",
      "valueSchema": "JmeTestCreatedEvent_v1.avdl"
    },
    {
      "version": "0.0.2",
      "valueSchema": "JmeTestCreatedEvent_v2.avdl",
      "compatibilityMode": "FULL"
    },
    {
      "version": "0.0.3",
      "valueSchema": "JmeTestCreatedEvent_v3.avdl",
      "compatibilityMode": "FULL"
    },
    {
      "version": "0.0.4",
      "valueSchema": "JmeTestCreatedEvent_v4.avdl",
      "compatibilityMode": "FULL"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmeordervalidatedevent/JmeOrderValidatedEvent.json
{
  "eventName": "JmeOrderValidatedEvent",
  "description": "Order validated (sequential inbox example)",
  "publishingSystem": "JME",
  "topic": "jme-order-validated",
  "scope": "public",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeOrderValidatedEvent_v1.avdl"
    },
    {
      "version": "1.1.0",
      "valueSchema": "JmeOrderValidatedEvent_v1.1.0.avdl",
      "compatibilityMode": "FORWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmeracemobilecheckpointpassedevent/JmeRaceMobileCheckpointPassedEvent.json
{
  "eventName": "JmeRaceMobileCheckpointPassedEvent",
  "description": "Racer passed a mobile checkpoint",
  "publishingSystem": "JME",
  "scope": "internal",
  "topic": "jme-race-mobilecheckpoint-passed",
  "versions": [
    {
      "version": "1.1.0",
      "valueSchema": "JmeRaceMobileCheckpointPassedEvent_v1.avdl"
    },
    {
      "version": "1.2.0",
      "valueSchema": "JmeRaceMobileCheckpointPassedEvent_v2.avdl"
    },
    {
      "version": "1.2.1",
      "valueSchema": "JmeRaceMobileCheckpointPassedEvent_v1.2.1.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmetransitdecisioncreatedevent/JmeTransitDecisionCreatedEvent.json
{
  "eventName": "JmeTransitDecisionCreatedEvent",
  "publishingSystem": "JME",
  "description": "Notification that a decision on a transit document has been made (OpenSearch example service).",
  "topic": "jme-transit-decision-created",
  "scope": "internal",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeTransitDecisionCreatedEvent_v1.0.0.avdl",
      "compatibilityMode": "FULL"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmeracepreparedevent/JmeRacePreparedEvent.json
{
  "eventName": "JmeRacePreparedEvent",
  "publishingSystem": "JME",
  "description": "Notification that a race has been prepared for a race car.",
  "topic": "jme-race-prepared",
  "scope": "internal",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeRacePreparedEvent_v1.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmedocumentversionreviewedevent/JmeDocumentVersionReviewedEvent.json
{
  "eventName": "JmeDocumentVersionReviewedEvent",
  "publishingSystem": "JME",
  "description": "Notification that a document version has been reviewed.",
  "documentationUrl": "https://confluence.bit.admin.ch/display/JEAP/TODO",
  "topic": "jme-document-version-reviewed",
  "scope": "internal",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeDocumentVersionReviewedEvent_v1.0.0.avdl",
      "compatibilityMode": "FORWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmeracecartirepressurecheckedevent/JmeRaceCarTirePressureCheckedEvent.json
{
  "eventName": "JmeRaceCarTirePressureCheckedEvent",
  "description": "Race car tire pressure check completed",
  "publishingSystem": "JME",
  "topic": "jme-race-tire-pressure-checked",
  "scope": "internal",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeRaceCarTirePressureCheckedEvent_v1.avdl"
    },
    {
      "version": "2.0.0",
      "valueSchema": "JmeRaceCarTirePressureCheckedEvent_v2.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}
