=== jme-admin-ch/jme-message-type-registry/schema/EventDescriptor.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Event Descriptor",
  "description": "JSON schema for event descriptors",
  "$ref": "#/definitions/EventDescriptor",
  "definitions": {
    "EventDescriptor": {
      "type": "object",
      "properties": {
        "eventName": {
          "type": "string",
          "minLength": 10
        },
        "definingSystem": {
          "type": "string",
          "minLength": 2
        },
        "publishingSystem": {
          "type": "string",
          "minLength": 2,
          "$comment": "deprecated - use definingSystem"
        },
        "description": {
          "type": "string"
        },
        "documentationUrl": {
          "$ref": "common.schema.json#/definitions/url"
        },
        "scope": {
          "type": "string",
          "enum": [
            "public",
            "internal"
          ]
        },
        "topic": {
          "type": "string"
        },
        "compatibilityMode": {
          "$ref": "common.schema.json#/definitions/compatibilityMode"
        },
        "versions": {
          "$ref": "common.schema.json#/definitions/Versions"
        }
      },
      "required": [
        "eventName",
        "description",
        "scope"
      ],
      "anyOf": [
        {
          "required": [
            "publishingSystem"
          ]
        },
        {
          "required": [
            "definingSystem"
          ]
        }
      ],
      "additionalProperties": false
    }
  }
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmeraceobjectsonroadspottedevent/JmeRaceObjectsOnRoadSpottedEvent.json
{
  "eventName": "JmeRaceObjectsOnRoadSpottedEvent",
  "description": "Objects on roads spotted",
  "publishingSystem": "JME",
  "topic": "jme-race-objects-spotted",
  "scope": "internal",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeRaceObjectsOnRoadSpottedEvent_v1.avdl"
    },
    {
      "version": "1.1.0",
      "valueSchema": "JmeRaceObjectsOnRoadSpottedEvent_v2.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmegamereviewcreatedevent/JmeGameReviewCreatedEvent.json
{
  "eventName": "JmeGameReviewCreatedEvent",
  "publishingSystem": "JME",
  "description": "A game review has been created",
  "documentationUrl": "https://confluence.bit.admin.ch/display/JEAP/JmeGameReviewCreatedEvent",
  "topic": "jme-crypto-game-review-created",
  "scope": "internal",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeGameReviewCreatedEvent_v1.avdl",
      "compatibilityMode": "FORWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmeraceweatheralertactivatedevent/JmeRaceWeatherAlertActivatedEvent.json
{
  "eventName": "JmeRaceWeatherAlertActivatedEvent",
  "description": "Weather alert activated for a race course",
  "publishingSystem": "JME",
  "topic": "jme-race-weather-alert-activated",
  "scope": "public",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeRaceWeatherAlertActivatedEvent_v1.0.0.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmeracecarrefuellingcompletedevent/JmeRaceCarRefuellingCompletedEvent.json
{
  "eventName": "JmeRaceCarRefuellingCompletedEvent",
  "description": "Racer car is fuelled up.",
  "publishingSystem": "JME",
  "topic": "jme-race-refuelling-completed",
  "scope": "internal",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeRaceCarRefuellingCompletedEvent_v1.avdl",
      "compatibilityMode": "BACKWARD"
    },
    {
      "version": "2.0.0",
      "valueSchema": "JmeRaceCarRefuellingCompletedEvent_v2.avdl",
      "compatibilityMode": "FULL"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmedocumentcreatedevent/JmeDocumentCreatedEvent.json
{
  "eventName": "JmeDocumentCreatedEvent",
  "publishingSystem": "JME",
  "description": "Notification that a document has been created",
  "documentationUrl": "https://confluence.bit.admin.ch/display/JEAP/TODO",
  "topic": "jme-document-created",
  "scope": "internal",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeDocumentCreatedEvent_v1.0.0.avdl",
      "compatibilityMode": "FORWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmeracevalidatedevent/JmeRaceValidatedEvent.json
{
  "eventName": "JmeRaceValidatedEvent",
  "description": "Race has been validated",
  "publishingSystem": "JME",
  "topic": "jme-race-validated",
  "scope": "public",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeRaceValidatedEvent_v1.avdl",
      "compatibilityMode": "BACKWARD"
    },
    {
      "version": "1.2.0",
      "valueSchema": "JmeRaceValidatedEvent_v2.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmedecreecreatedevent/JmeDecreeCreatedEvent.json
{
  "eventName": "JmeDecreeCreatedEvent",
  "publishingSystem": "JME",
  "description": "Notification that a decree has been created.",
  "documentationUrl": "https://confluence.bit.admin.ch/display/JEAP/TODO",
  "topic": "jme-process-archive-decreecreated",
  "scope": "internal",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeDecreeCreatedEvent_v1.0.0.avdl",
      "compatibilityMode": "FORWARD"
    }
  ]
}

=== jme-admin-ch/jme-message-type-registry/descriptor/jme/event/jmeracecontrolpointpassedevent/JmeRaceControlpointPassedEvent.json
{
  "eventName": "JmeRaceControlpointPassedEvent",
  "description": "Racer passed a control point",
  "publishingSystem": "JME",
  "scope": "internal",
  "topic": "jme-race-controlpoint-passed",
  "versions": [
    {
      "version": "1.1.0",
      "valueSchema": "JmeRaceControlpointPassedEvent_v1.avdl"
    },
    {
      "version": "1.1.1",
      "valueSchema": "JmeRaceControlpointPassedEvent_v1.1.1.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}
